apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-product
  labels:
    app: demo-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-product
  template:
    metadata:
      labels:
        app: demo-product
    spec:
      containers:
      - name: demo-product
        image: nexweb1/demo-zipkin-product:0.2
        ports:
        - containerPort: 8081
        env:
        - name: ZIPKIN_HOST
          value: zipkin
        - name: ZIPKIN_PORT
          value: "9411"